### ISSUE TITLE
Instance Tags support

### ISSUE THREAD

**Issue by ActualMasterOogway** [uniquadev/GuiToLuaConverter#10]
Support for Instance Tags
https://create.roblox.com/docs/reference/engine/classes/CollectionService#GetTags
https://create.roblox.com/docs/reference/engine/classes/CollectionService#AddTag

**Comment by uniquadev** [comment]
Time to implement It?

**Comment by ActualMasterOogway** [comment]
> Time to implement It?

I was on vacation when i wrote that, completely forgot about this.
Will work on this right now
