### ISSUE TITLE
Idk if it my computer but whenever I use the plugin my games crashes.

### ISSUE THREAD

**Issue by TrueKevinGamer** [uniquadev/GuiToLuaConverter#8]
windows 11

**Comment by LucaBarbaLata** [comment]
have you tried reinstalling roblox studio or reactivating the plugin?

**Comment by uniquadev** [comment]
I assume that when you talk about "game crashes" you refer to Roblox Studio..

The plugin has been thoroughly tested many times, and we have not encountered any issues with it causing crashes in Roblox Studio. 

Thank you for bringing to our attention the issue you are experiencing with our plugin.
Please note that if we do not hear from you within the next week, we will consider this issue closed.
